workflows:
  ios-native-quick-start:
    name: MyMotivation
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CM Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.activ.motivation
      vars:
        XCODE_PROJECT: "MyMotivation.xcodeproj"
        XCODE_SCHEME: "MyMotivation"
        BUNDLE_ID: " com.activ.motivation"
        #XCODE_WORKSPACE: "MyMotivation.xcodeproj"
        #XCODE_SCHEME: "MyMotivation"
        APP_STORE_APPLE_ID: 6762372863
      xcode: 16.4
      cocoapods: default
      
    script: |
      echo "CM_BUILD_DIR=$CM_BUILD_DIR"
      echo "PWD=$(pwd)"

      echo "=== Xcode projects ==="
      find "$CM_BUILD_DIR" -name "*.xcodeproj" -print

      echo "=== Info.plist files ==="
      find "$CM_BUILD_DIR" -name "Info.plist" -print

      echo "=== project.pbxproj ==="
      find "$CM_BUILD_DIR" -name "project.pbxproj" -print
      
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      #- $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      #- $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
     # email:
        #recipients:
        #notify:
          #success: true
          #failure: false
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional).
        # Note: This action is performed during post-processing.
        submit_to_testflight: false
        #beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          #- group name 1
          #- group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        # submit_to_app_store: false
